config/routes.rb
InstaApp::Application.routes.draw do
  match '/about',   to: 'home#about'
  match '/home',    to: 'home#index'
  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'json'
  def index
        result = []
        next_id = nil
        pages = 0;
        while pages < 5
            data = Instagram.tag_recent_media("geisel", max_id: next_id)
            next_id = data.pagination.next_max_id
            result.concat(data)
            pages += 1
        end

        @results = result.paginate(:page => params[:page], :per_page => 30)

          if request.xhr?
            render '_photos'
          end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_photos.html.erb
<% @results.each do |instagram| %>
<% if instagram.caption != nil
    caption_text = instagram.caption.text
  end %>
<% title_text = caption_text.to_s + '<br/>' + '<strong><a target="_blank" href = "http://instagram.com/' + instagram.user.username.to_s + '">' + instagram.user.username.to_s + '</a></strong>'  + ' ' + instagram.likes[:count].to_s + ' Likes' + '<br/>' + '<a target="_blank" href = "' + instagram.link.to_s + '">' + 'View on Instagram' + '</a>'%>
  <div class = "image-display">
    <div class = "overlay">
      <%= link_to image_tag(instagram.images.standard_resolution.url, class: "tagged-images"), instagram.images.standard_resolution.url, :class => "fancybox", :title => title_text %>
    </div>
  </div>
<% end %>
<%= will_paginate @results %>
<script> 
jQuery(function() {
  $("a.fancybox").fancybox({
            'transitionIn'      : 'fade',
            'transitionOut'     : 'fade',
            'titleFormat'       : function(title) {
                return title;
            },
              beforeShow: function(){
      $("body").css({'overflow-y':'hidden'});
    },
    afterClose: function(){
      $("body").css({'overflow-y':'visible'});
    },
            helpers : {
              title: {
                type: 'inside',
                position: 'bottom'
              },
                  overlay: {
      locked: false
    }
            },

  });

});
</script>
<!-- instagram.caption.text
instagram.user.username
instagram.likes[:count]

 -->

app/views/home/_test.html.erb
<div class = "title-text">
  Geisel Library
</div>


<div class = "subtitle-text">
    <p class="lead">
  University of California San Diego
</p>
</div>

app/views/home/about.html.erb
    <div class="full-width-image-1">

        <div class="logo-wrapper">
        </div>

    </div>
    <!-- /full-width-image-1 -->

    <div class="container">
        <div class="row">
            <div class="col-lg-12 section">
                <h1 class="section-heading">About the UC San Diego Library</h1>
                <p class="lead section-lead">The UC San Diego Library provides access to more than 7 million digital and print volumes, journals, and multimedia materials to meet the knowledge demands of scholars, students, and members of the public. </p>
                <p class="section-paragraph">Great research starts here.  The UC San Diego Library, ranked among the nation's top 25 public academic libraries, plays a critical role in advancing and supporting the university's research, teaching, patient care, and public service missions. The world-renowned research for which UC San Diego is known starts at the UC San Diego Library, which provides the foundation of knowledge needed to advance cutting-edge discoveries in a wide range of disciplines, from healthcare and science to public policy and the arts.</p>
            </div>
        </div>
    </div>

    <div class="full-width-image-2">
        <!-- box content goes here if you want to put text or a button in here -->
    </div>
    <!-- /full-width-image-2 -->

    <div class="container">
        <div class="row">
            <div class="col-lg-12 section">
                <h1 class="section-heading">Technology Leaders Advancing Scholarship</h1>
                <p class="lead section-lead">The UC San Diego Library is widely recognized as an innovative leader in the development, management, and delivery of digital resources to support the university's world-class research and instruction. </p>
                <p class="section-paragraph">The first academic library in Southern California to partner with Google in its efforts to build a global digital library, the Library plays a leadership role in HathiTrust, an international partnership of 52 academic and research libraries committed to long-term digital preservation. The Library is also a partner in the university’s Research Cyberinfrastucture Initiative (RCI), which offers researchers the computing, network, and human infrastructure needed to create, manage, and share data.</p>
            </div>
        </div>
    </div>

    <!-- FOOTER -->
    <div class="container">
      <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Alex Yang 2014
                </div>
            </div>
        </footer>
    </div>

    </div>

app/views/home/index.html.erb
<div class = "home-space">
<div class = "title-text">
  Geisel Library
</div>


<div class = "subtitle-text">
    <p class="lead">
  University of California San Diego
</p>
</div>

<div class = "tagged-images-container ">
  <div class = "tagged-images-container-position">
    <%= render :partial => 'photos' %>
  </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- Magnific Popup core CSS file -->
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Library</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class = "container home">
<%= yield %> 
</div>
<div class="modal"><!-- Place at bottom of page --></div>
</body>
</html>